rulesets:
  - name: Branches rulesets
    rules:
      pull_request:
        required_approving_review_count: 1
        required_approvals: 2
        require_code_owner_review: true  
      required_status_checks:
        required_checks:
          - GitGuardian
          - GitGuardian Security Checks
