rulesets:
  - name: Branches rulesets
    rules:
      pull_request:
        required_approvals: 2
        dismiss_stale_reviews_on_push: true
        require_code_owner_review: true  
custom_properties:
  minimum-approvals:
    value: 3
